apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: staging
patchesJson6902:
- target:
    group: batch
    version: v1
    kind: CronJob
    name: rethinkdb-rotator
  path: env.yml