apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yml
  - services.yml
  - deployment.yml
  - sa.yml
  - role.yml
  - rolebinding.yml
  - cronjob.yml
# When a Secret is generated, the Secret name is created by hashing the Secret data and 
# appending the hash value to the name. 
# This ensures that a new Secret is generated each time the data is modified.
secretGenerator:
  - name: rethinkdb-client-pass
    files:
    - username.txt
    - password.txt