apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rotator-role-binding
subjects:
- kind: ServiceAccount
  name: rotator-sa
roleRef:
  kind: Role
  name: rotator-role
  apiGroup: rbac.authorization.k8s.io