apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-fastapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: rethinkdb-fastapi
